name: Build yt-dlp on Mac OS

on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install source
        run: git clone --depth 1 https://github.com/yt-dlp/yt-dlp.git

      - name: Install build dependencies
        run: pip3 install Pyinstaller mutagen pycryptodomex websockets

      - name: Create package
        run: |
            cp pyinst-mac.py yt-dlp
            cd yt-dlp
            python3 ./pyinst-mac.py
            chmod 755 dist/yt-dlp

      - name: Create artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v2
        with:
          name: yt-dlp
          path: yt-dlp/dist/yt-dlp
