name: Build snap package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Get name
        run: |
            filename=`ls *.snap`
            echo "PACKAGEFILENAME=$filename" >> $GITHUB_ENV

      - name: Create artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGEFILENAME }}
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.snapcraft.outputs.snap }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
