name: Build yt-dlp on Mac OS

on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install source
        run: git clone --depth 1 https://github.com/yt-dlp/yt-dlp.git

      - name: Install build dependencies
        run: pip3 install Pyinstaller mutagen pycryptodomex websockets certifi

      - name: Create package
        run: |
            cp pyinst.py yt-dlp
            cd yt-dlp
            python3 ./pyinst.py

      - name: Create artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v2
        with:
          name: yt-dlp_macos
          path: yt-dlp/dist/yt-dlp_macos

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: yt-dlp/dist/yt-dlp_macos
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
